name = "ubiquibot"
account_id = "84f5ebd30e5caca102add77e020d3be2"
workers_dev = true

main = "functions/webhooks/worker.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2023-07-14"